//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKT.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apprd.skplanet.com:80/comn/webservices.nsf/wsEncryptedString?OpenWebServic" +
            "e")]
        public string SKT_Common_NotesEncryptService_wsEncryptedStringServie {
            get {
                return ((string)(this["SKT_Common_NotesEncryptService_wsEncryptedStringServie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erp_prod.sktelecom.com:8000/sap/bc/srt/rfc/sap/zehr_pt_list_view/501/zehr_" +
            "pt_list_view/zehr_pt_list_view")]
        public string SKT_Common_com_sktelecom_erp_prod_ZEHR_PT_LIST_VIEW {
            get {
                return ((string)(this["SKT_Common_com_sktelecom_erp_prod_ZEHR_PT_LIST_VIEW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SK Telecom Common")]
        public string group {
            get {
                return ((string)(this["group"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cspcbh.sktelecom.com:8080/ws/cbh/MailService")]
        public string SKT_Common_CBH_Mail_MailSenderService {
            get {
                return ((string)(this["SKT_Common_CBH_Mail_MailSenderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cspcbh.sktelecom.com:8080/ws/cbh/SKTSOAWeb/NoteService")]
        public string SKT_Common_CBH_Note_NoteServiceService {
            get {
                return ((string)(this["SKT_Common_CBH_Note_NoteServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cspcbh.sktelecom.com:8080/ws/cbh/SMSService")]
        public string SKT_Common_CBH_SMS_SMSSenderService {
            get {
                return ((string)(this["SKT_Common_CBH_SMS_SMSSenderService"]));
            }
        }
    }
}
