//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace SKT.Common.CBH_Note {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NoteServiceServiceSoapBinding", Namespace="http://skt/soa/sample/webservice/test")]
    public partial class NoteServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendNoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NoteServiceService() {
            this.Url = global::SKT.Common.Properties.Settings.Default.SKT_Common_CBH_Note_NoteServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendNoteCompletedEventHandler sendNoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://skt/soa/sample/webservice/test", ResponseNamespace="http://skt/soa/sample/webservice/test", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string sendNote(string P_SENDUSERID, string P_SENDUSERNAME, string P_TARGETUSER, string P_CONTENT, string P_URL, string P_KIND) {
            object[] results = this.Invoke("sendNote", new object[] {
                        P_SENDUSERID,
                        P_SENDUSERNAME,
                        P_TARGETUSER,
                        P_CONTENT,
                        P_URL,
                        P_KIND});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendNoteAsync(string P_SENDUSERID, string P_SENDUSERNAME, string P_TARGETUSER, string P_CONTENT, string P_URL, string P_KIND) {
            this.sendNoteAsync(P_SENDUSERID, P_SENDUSERNAME, P_TARGETUSER, P_CONTENT, P_URL, P_KIND, null);
        }
        
        /// <remarks/>
        public void sendNoteAsync(string P_SENDUSERID, string P_SENDUSERNAME, string P_TARGETUSER, string P_CONTENT, string P_URL, string P_KIND, object userState) {
            if ((this.sendNoteOperationCompleted == null)) {
                this.sendNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendNoteOperationCompleted);
            }
            this.InvokeAsync("sendNote", new object[] {
                        P_SENDUSERID,
                        P_SENDUSERNAME,
                        P_TARGETUSER,
                        P_CONTENT,
                        P_URL,
                        P_KIND}, this.sendNoteOperationCompleted, userState);
        }
        
        private void OnsendNoteOperationCompleted(object arg) {
            if ((this.sendNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendNoteCompleted(this, new sendNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sendNoteCompletedEventHandler(object sender, sendNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591